version: "3.9"
services:
  worker:
    build: .
    environment:
      - API_HASH=${API_HASH}
      - API_ID=${API_ID}
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_URI=${DB_URI}
      - USER_SESSION=${USER_SESSION}
